version: '2'

services:

  web:
    build:
      context: .
    container_name: textannot
    image: udlepssoftarch/textannot-api
    networks:
      - brigenet
    ports:
      - '4200:4200'
    environment:
    - PORT=4200

networks:
  brigenet:
    driver: bridge
